import { Language } from './types';

export const TRANSLATIONS = {
  tr: {
    nav_expert: 'Uzman',
    partner_form_title: 'Bayilik Başvurusu',
    pharmacy_name_label: 'Kurum / Şube Adı',
    pharmacy_placeholder: 'Örn: Nişantaşı Şubesi',
    applicant_name_label: 'Ad Soyad',
    applicant_name_placeholder: 'Adınızı ve soyadınızı giriniz',
    contact_label: 'İletişim (Tel/E-posta)',
    form_success: 'Başvurunuz başarıyla iletildi. En kısa sürede iletişime geçeceğiz.',
    form_success_sub: 'Telegram üzerinden bilgilendirme iletildi.',
    app_request_title: 'UZMAN BAŞVURUSU',
    app_request_subtitle: 'Protokol V2.0',
    app_request_desc: 'Profesyonel uygulama etkinliği planlamak için formu doldurun.',
    app_time_label: 'Uygulama Saati',
    btn_request_app: 'Katılım Talep Et',
    app_exclusive_badge: 'Özel',
    form_missing: 'Lütfen tüm alanları doldurunuz.',
    ai_error: 'Bağlantı hatası oluştu.',
    btn_view_formula: 'FORMÜLÜ İNCELE',
    role_label: 'Yetki Ünvanı',
    role_pharmacist: 'İşveren',
    role_assistant: 'Uzman',
    registration_form: 'Katılım Formu',
  },
  en: {
    nav_expert: 'Expert',
    partner_form_title: 'Partnership Application',
    pharmacy_name_label: 'Pharmacy Name',
    pharmacy_placeholder: 'e.g. Acacia Pharmacy',
    applicant_name_label: 'Full Name',
    applicant_name_placeholder: 'Enter your full name',
    contact_label: 'Contact Info (Tel/Email)',
    form_success: 'Your application has been sent successfully. We will contact you soon.',
    form_success_sub: 'Notification sent via Telegram.',
    app_request_title: 'EXPERT APPLICATION',
    app_request_subtitle: 'Protocol V2.0',
    app_request_desc: 'Fill in the form to schedule a professional application event at your pharmacy.',
    app_time_label: 'Application Time',
    btn_request_app: 'Request Application',
    app_exclusive_badge: 'Exclusive Series',
    form_missing: 'Please fill in all fields.',
    ai_error: 'Connection error occurred.',
    btn_view_formula: 'VIEW FORMULA',
    role_label: 'Authority Title',
    role_pharmacist: 'Pharmacist',
    role_assistant: 'Pharmacy Assistant',
    registration_form: 'Registration Form',
  }
};

export const EXCELLENCE_V2_INGREDIENTS = [
  "Hydrolyzed Collagen",
  "Helianthus Annuus Seed Oil",
  "Prunus Cerasus Seed Oil",
  "Ranunculus Ficaria Extract",
  "Persea Gratissima Oil",
  "Calendula Officinalis Seed Oil",
  "Caprylic/Capric Triglyceride",
  "Panthenol",
  "Polysorbate 20",
  "Lavandula Angustifolia Oil",
  "Tocopheryl Acetate",
  "Resveratrol"
];
